priyankarpal/projectshut

README.md
=> Added  new title

index.html
- added my college project - Phonebook Management System
=> new: Phonebook Management System

contributing.md, index.html
=> Priyankarpal

index.html
Removed an emoji
PLease add screenshots
Please list any related issues that your PR addresses. For example, if you fixed a bug, please reference the issue number that describes the bug.
=> Removed an emoji

README.md
Spelling fix at line number 21
Is there anything else you would like to include about your PR? This could include information about how to test your changes or any potential issues that may arise.
=> Spelling fix at line number 21

index.html
Project Razorpay Clone added 
Please describe the changes you made to the Projectshut Open Source website. What features did you add or modify? What bug did you fix?
I just added a new project 
Please list any related issues that your PR addresses. For example, if you fixed a bug, please reference the issue number that describes the bug.
Is there anything else you would like to include about your PR? This could include information about how to test your changes or any potential issues that may arise.
=> New project added

contributing.md, index.html, tailwind.config.js
1. logo removed
2.  (Query resolved) : font-style specified in tailwind.config.js
Please describe the changes you made to the Projectshut Open Source website. What features did you add or modify? What bug did you fix?
-> fixed font style issue
-> logo removed as asked
Please list any related issues that your PR addresses. For example, if you fixed a bug, please reference the issue number that describes the bug.
=> Query resolved

index.html, tailwind.config.js
Reverts priyankarpal/ProjectsHut#29
=> Revert "Query resolved"

index.html
1. Resolved bug during "Merge Conflict"
2. font issue resolved in tailwind.config.js
3. removed logo as asked
=> resolved Merge conflict bug

tailwind.config.js
font-family fixed (merge conflict bug)
=> font-family fixed

index.html
=> font-family api

index.html
The font has been changed to ui-monospace and the font weight reduced to Light
**Enhancing the Font weight of "ProjectHut" , I felt like reducing its weight to font-light**
Also the font family doesn't fit the heading and was changed to **monospace**
=> Font changed and Font weight reduced

index.html
=> add social links to footer

index.html
=> favicon changed

index.html
=> new card added

index.html, package-lock.json, package.json
I have updated my project card.
=> Project card Updated. 

src/projects.json
Added mt projects made using ReactJs
=> Added My Project

src/App.jsx
Changed the exact path to path and 404 page error was solved
=> chaged the path of 404

src/DB/projects.json
=> Adding a project

src/DB/projects.json
I reformatted `projects.json` file.
=> fix: reformat

src/DB/projects.json
=> add: project

src/DB/projects.json
This is a solution to the [QR code component challenge on Frontend Mentor](https://www.frontendmentor.io/challenges/qr-code-component-iux_sIO_H). Frontend Mentor challenges help you improve your coding skills by building realistic projects.
=> QR code component added by Gyan

src/DB/projects.json
=> Add project

src/DB/projects.json
=> add my project

README.md, translations/Spanish/CODE_OF_CONDUCT.md, translations/Spanish/README.md, translations/Spanish/contributing.md
=> issue #95 - adding spanish translation

src/DB/projects.json
Removed Empty Projects - SpaceX Clone 
And One More Project Under The Same Name - SpaceX Clone
This PR resolves the issue number #69 
It would be great if you thoroughly review the PRs before merging them to see any discrepancy and empty projects. Of course I would help as much as I can to maintain the quality of this project...........Thanks
=> Updated Projects Database [Issue Number #69]

src/CSS/index.css
Changed color of default scroll-bar with foreground white and background black
none
=> custom scrollbar

src/CSS/index.css
=> chore: code formatted & deleted a comment

src/CSS/index.css
optimised scroll-bar for almost all browsers
ISSUE #113 
=> fix: scroll-bar

README.md, src/components/Navbar.jsx, src/pages/HomePage.jsx
Changed browse projects button hover background hover color.
=> <Feat> Changed button hover color

src/DB/projects.json
The project added to the DB file
=> chore: an open source project called Invester added

README.md
Corrected a minor typo in README.md
=> Correct typo in readme.md

src/components/ProjectCard.jsx
Added a hover effect to the github link on the ProjectCard using tailwind
Buttons that had the hover effect added 
N/A
=> Added hover effect to github links using tailwind

README.md
Refactor: Added a message "Remember to add a good commit message" to the README.md file. And a tweet link of priyankarpal to refer "How to write professional commits"
=> Added a "Remember to add a good commit message"

.eslintrc.cjs, .husky/pre-commit, package.json, pnpm-lock.yaml, src/components/Footer.jsx, src/components/ProjectCard.jsx, src/pages/ProjectsPage.jsx
- Added line clamp to avoid long descriptions
=> chore: added line clamp 👽

README.md
- Addition of a new point under the `How to contribute?` section of the README file.
- This is basically a `Documentation` update, where I have added a new point under the `How to contribute?` section of the README file.
=> add a new point in README file

src/DB/projects.json
Adds my project "Chromatico" in the project list
=> chore: adds my project chromatico

src/pages/ProjectsPage.jsx
Redesigned the header on the Projects page, and also removed extra spaces in that file to maintain code structure.
This PR closes issue #155
=> chore: redesigned the header on projects page

README.md
=> Added tech stacks in readme.md

src/components/Navbar.jsx, src/pages/ProjectsPage.jsx
Removed extra margin for mobile view in the projects section and fixed the navbar logo. #161
=> fixed extra padding/margin from both side for mobile view in the projects section.

README.md
- Added the `Vercel` logo in the README file.
- It's a `Documentation` update where a new logo has been added to the README file.
=> Logo addition in README

src/DB/projects.json
- Added my project `TrailBlaze` in the `src/DB/projects.json`.
- `Project addition`
=> Project addition for the Website

src/DB/projects.json
=> added portfolio project

src/pages/HomePage.jsx
1) I  have changed color to white which is more good ..
2) I have added arrow beside button..
=> fix: changed the button style #159

src/components/Banner.jsx
Before documentation text was not in box which was less attractive but now i have given it  a box which is more attractive and good.
=> fix: added box button #164

pnpm-lock.yaml, src/components/ProjectCard.jsx, src/pages/ProjectsPage.jsx, src/utils/paginate.js
As described in #178 , a pagination system has been added. Also, line clamp is added to Product Card title.
In case of tech-labels in Product-Card, usage of line-clamp property shows inappropriate behavior (as shown below) . Therefore, JS is used for maintaining the length of the line.
=> Implemented Pagination

src/DB/projects.json
=> Added "Swapnoneel's Portfolio" Project

src/App.jsx, src/components/SplashScreen.jsx
https://user-images.githubusercontent.com/103263909/232324460-73b53426-9bda-4ee9-af25-409241346b81.mp4
=> Splash Screen Added

src/pages/ProjectsPage.jsx
Changed the link under  Check Documentation
=>  Check Documentation

src/components/Navbar.jsx
Created a box for contributors button and given a arrow beside it which is more attractive
=> Completed adding the function

src/pages/HomePage.jsx, src/pages/ProjectsPage.jsx
1. h1 line height and font size fixed on homepage
2. Background color on hover on buttons in projects page added.
closes #212  
closes #213
=> <FIX>h1 and hover effect on buttons fixed

src/DB/projects.json, src/components/Footer.jsx, src/components/Navbar.jsx
I have removed the share on twitter button and the twitter logo from the footer section..
Issue no #226
=> Footer section

src/DB/projects.json
=> added new project

src/DB/projects.json, src/components/Footer.jsx, src/components/Navbar.jsx
I have added Discord icon in the Navbar with the link of ProjectsHut
=> Adding of discord icon

src/CSS/index.css, src/pages/HomePage.jsx
=> Fixed the browse projects btn not be overlaid by other elements

src/components/Navbar.jsx, src/components/SideMenu.jsx
=>  fix: added ul & li instead of div #247

src/DB/projects.json
added digital media agency landing page template
=> Chore: added digital media agency landing page template

src/App.jsx, src/components/ScrollToTop.js, src/pages/ProjectsPage.jsx
Added scroll to top effect whenever pages are changed
and also when page number( in projectpage ) is clicked, page scrolls to top
=> Scroll to top on page changes

README.md
I try to write the introductory part of the ProjectsHut with my best.
I have rewritten the introductory part of the project.
- [x ] I have included documentation for any new features or changes
=> re write the Projectshut introduction

README.md
I have tried to improve the tech stack used paragraph.
I have tried to improve the tech stack used section of the readme.
- [x ] I have included documentation for any new features or changes
=> docs: changes README

src/components/Navbar.jsx, src/context/Theme.jsx
just changed the size of icons & emoji changed also
=> chore: icons size changed & emoji changed

src/components/Navbar.jsx
=> fix: typo on Navbar.jsx

src/components/Footer.jsx
=> feat: footer redesigned #235

src/components/Footer.jsx, src/context/Theme.jsx
=> #267:make text visible on both dark and light mode

src/components/Navbar.jsx, src/context/Theme.jsx
This PR fixes the icons alignment issue on NavBar reported in [#269](https://github.com/priyankarpal/ProjectsHut/issues/269)
=> fix: alignment of navbar icons  #269

src/components/Footer.jsx
=> Centered the text Under MIT License

src/CSS/index.css, src/pages/HomePage.jsx
=> Bug: Added padding btw btn and img in homepage

src/App.jsx
This PR refactors routes according to `react-router-dom` v6. `exact` is now a default behavior so we do not need to add it explicitly.
=> :refactor: update routes according to v6 #278

src/components/Navbar.jsx
This PR fixes the issue related to the sidebar.
https://user-images.githubusercontent.com/88369802/234557778-1c1726da-885a-43cb-a27a-066136cb2657.mov
=> fix: sidebar not appearing for certain width #281

translations/translation_guide.md
- [x ] I have checked for any spelling or grammatical errors
=> corrected a very minor spelling mistake in  translation_guide.md

translations/German/CODE_OF_CONDUCT.md, translations/German/README.md, translations/German/contributing.md
- #285 
- [ x] I have updated the README and any other relevant documentation
- [ x] I have checked for any spelling or grammatical errors
=> Translated the doc to german

translations/translation_guide.md
- [ x] I have updated the README and any other relevant documentation
- [x ] I have checked for any spelling or grammatical errors
=> listed out some missing translated language in translation_guide.md

src/DB/projects.json
=> Added sagar1621 profile to projects.json

translations/German/README.md, translations/Spanish/README.md, translations/translation_guide.md
…Spanish
- [x ] I have updated the README and any other relevant documentation
=> updated the list of available languages and minor transaltion fix 

.github/workflows/quality_check.yml, package.json, pnpm-lock.yaml
This PR adds Quality Check github action.
=> feat: add quality check github action #304

contributing.md
- whenever you create a PR/issue please add a good title & description
- add good commit messages
- add screenshots if needed
Fixed #313
=> docs: added few points #313

src/components/ProjectList.jsx
Fixed #315 
Changed some ui designs
=> style: change `projectspage/:username` designs #315

.github/ISSUE_TEMPLATE/style.yml
fixed #317
- Added style.yml issue template
=> feat: Create style.yml #317

src/DB/projects.json
=> [Feat] : Add Project Courseify

__tests__/pages/HomePage.test.jsx, index.html, src/App.jsx, src/components/Navbar.jsx, src/components/ProjectCard.jsx, src/components/ProjectList.jsx, src/components/SideMenu.jsx, src/context/Theme.jsx, src/pages/HomePage.jsx, tailwind.config.cjs
=> style: improved nav bar style, changed font familly

README.md
=> docs: change the image #327

.github/PULL_REQUEST_TEMPLATE.md
=> chore: Update PULL_REQUEST_TEMPLATE.md  #337

.github/PULL_REQUEST_TEMPLATE.md, translations/translation_guide.md
#338 
due to a format issue, I run pnpm format and some changes were made. i don't know anything about it these changes.
=> translation guide update 

src/components/ProjectCard.jsx
Hover animation is removed from Project cards to enhance user-experience.
fixed #334
=> #334 Remove cards animation

src/DB/projects.json
- added oyepriyansh's projects
=> data: add oyepriyansh's projects

README.md
=> Update README.md #351

__tests__/components/SplashScreen.test.jsx, jsconfig.json, package.json, pnpm-lock.yaml, vite.config.js
#353 
* Installed **jest** and **testing-library/jest-dom**; this will allow for the use of `toBeInTheDocument()` matcher in all tests.
* Shorten js imports with aliases - this will prevent the use of **../../../FileName.ext** in the project files. Imports can be made using **@/components/** or **@/dirName/**.
* Wrote a test for the **SplashScreen** component.
=> test: SplashScreen component

src/DB/projects.json
=> project addition: added react project

src/DB/projects.json
This project link is routing to the project before it so i fixed it with the correct link
=> Update projects.json - Fixed a wrong project link

contributing.md
Add some changes to the documentation.
ISSUE_NUMBER: #410
=> docs: change in contribution.md file #410

.github/workflows/issue-lock.yml
- added a gh action to lock issues
=> feat: Create issue-lock.yml #446

contributing.md
=> docs: update contributing.md

src/DB/projects.json
Added a new project :- Weather Website
#485 
Added a new Project (Weather Website)
=> Addition : Project Weather Website

src/components/Footer.jsx
Issue : #467
automatically update current year
=> dynamic-copyright

translations/French/README.md, translations/German/README.md, translations/Italian/README.md, translations/Japanese/README.md, translations/Malayalam/README.md, translations/Spanish/README.md, translations/Turkish/CODE_OF_CONDUCT.md, translations/Turkish/contributing.md, translations/Turkish/readme.md, translations/translation_guide.md
- This PR adds the Turkish translation of ProjectsHut's documentation, enabling Turkish users to access and understand the content.
=> [Docs]: Add Turkish translation of ProjectsHut's docs

contributing.md, src/DB/projects.json
#402 
- Made the "contribution through the local machine" steps much clear
- Added useful links for beginners
=> docs: 📄 Improved Contribution.md

src/DB/projects.json
Issue Number : #489
This is a Google Clone application built with React JS. It replicates the functionality of the Google search engine, providing a home page, search component, and search results page.
**Features**
- Home Page: The application displays a home page similar to the Google search page, with a search bar and buttons.
- Search Component: Users can enter search queries in the search bar and click the search button to initiate a search.
- Search Page: The application displays search results instantly without refreshing the page, providing a list of search results with page titles, snippets, and links.
<b>Home Page</b> <br/>
<b>Search Page</b> <br/>
=> data: project addition by akshaykamath45

src/DB/projects.json
- The app is a IP tracker with geo location.
- It allows users to search the web with ease and convenience. 
- The web application displays the location, city,time-zone, postal code, and region of the IP address that user enters.
- The web application also displays information about the name, domain, ISP, proxy, VPN, and Tor of the IP address.
- Users can also quickly re-search without having to return to the homepage to perform a new search.
- The app was built using HTML, CSS, JavaScript.
- Asynchronous programming is implemented through calling a Geolocation API by IPify. 
- leaflet open-source JavaScript library is used to display map
- CSS is used to style the layout and HTML elements. 
- Javascript is used to give functionalty to the web.
=> Added Vanilla Javascript Project GEoTrackerX

src/DB/projects.json
Issue Number #567 
data: project addition by Vilas Chavhan
I want to add my project Movie App which is similar to Netflix UI, The app shows the latest trending movies and tv shows, The user can get information about a particular movie or tv show, The user can add or remove movies or shows to their watchlist , The user can search for a specific movie or show.
=>  #567 data: project addition by vilas Chavhan

README.md, src/components/Navbar.jsx
#376 
Replaced the emoji for dark light mode with a toggle switch for better yser engagement
=> Added toggle switch to the navbar for light/dark mode

src/DB/projects.json
closes #581 
Added my Java programs.
nil
=> added-java-programs

src/DB/projects.json, src/components/Footer.jsx
#504 
Removed mt-4 from the p tag in footer and this fixed alignment issue in footer.
=> Fix issue 504

src/DB/projects.json, src/components/ProjectList.jsx
=> add back to project link

src/pages/ProjectsPage.jsx
Issue No : #388
Fix the pagination problem.
=> fix: solve pagination issue

src/DB/projects.json
Issue #659 
Added the project into the `projects.json`
=> data: project addition 'Github Finder' by Sanchitbajaj02

src/DB/projects.json
Fixes #619 
This project aims to give beginners kickstart their open-source journey.
=> data: project addition by Sriparno08

.github/ISSUE_TEMPLATE/project-add.yml, README.md, src/DB/projects.json, src/components/ProjectList.jsx
- **ISSUE** -idea is to change style of tags of tech-stack
**In Day Light Mode**
**In Dark Mode**
=> src/components/ProjectList.jsx updated style of tags of tech-stacks

.github/ISSUE_TEMPLATE/project-add.yml, pnpm-lock.yaml, src/components/Navbar.jsx, src/components/ProjectList.jsx
In accordance to issue no. #638 
Added the hover effects as stated over the social links of project adders and over the GitHub icon in the navbar.
[https://www.loom.com/share/e205b714b2ef43c29f046577c1ab1d7a](url)
=> added hover effects on the socials of users

README.md, translations/Tagalog/CODE_OF_CONDUCT.md, translations/Tagalog/README.md, translations/Tagalog/contributing.md
#675 
translate md files to tagalog
=> Added a translation for md files to tagalog language

src/CSS/index.css, src/components/Footer.jsx
Issue Number #601 
Improved Footer design
=> [style]: change footer UI design #601

src/DB/projects.json
Closed issue #590 
Added my Youtube Clone project. Contributed under the GSSoC'23 program.
=> Added YouTube Clone project

.env.example, contributing.md, src/DB/projects.json, src/pages/ProjectsPage.jsx, src/utils/techStack.js
fix issue number #684 
fix json file as the teck key value was not correct (due to which some project was not showing when doing sorting) and also updated contribute.md file so people can follow same naming convention when writing their tech name
as you can see localhost project 
and deploy project their is change in number of project 
and same goes for other tech
=> Fix issue #684 Bug in project.json file

src/components/ProjectList.jsx
This PR closes issue #717.
[before.webm](https://github.com/priyankarpal/ProjectsHut/assets/130365071/d7f38129-0f55-4fcb-9f19-79f6e3ef784a)
[after.webm](https://github.com/priyankarpal/ProjectsHut/assets/130365071/e4f0d1de-a5b7-4265-be4d-53abd76f5f47)
- src/components/ProjectList.jsx
Please review this PR.
Thanks
=> [style]: change hover color to purple according to theme #717

src/DB/projects.json
New Project Added @priyankarpal kindly merge it.
=> GitHub Profile Searcher

src/components/Footer.jsx
Missing "to" and "." in Paragraph is added
=> Missing 'to' and '.' in Paragraph added

src/DB/projects.json
project addition by ShreyaDhiman #761
#761 
Added my project Thrift | Step Towards Literacy
=> Project addition by ShreyaDhiman #761

src/DB/projects.json
Issue Number : #730
I have added link to the project
=> File Compressor project with link added

src/components/Navbar.jsx
Issue resolved: #775 
To resolve this issue, I have made the necessary changes to the code by adding a gap between the nav items.
=> Fix responsiveness bug (#775) in nav bar

src/DB/projects.json
closes #778 
I have added cafe website
=> data: project addition [cafe project]  #778

src/components/Footer.jsx, src/components/ScrollToTop.jsx
fixed other components overlapping scroll-to-top button and removed duplicate static button
=> bug: Scroll to top fixed #768

src/pages/AddYourProjectsGuide.jsx
I am in GSSOC'23, please add the label
Issue #669
Updated Sample code for the docs page according to `contribution.MD`
=> Issue#669 GSSOC'23

src/DB/projects.json
Issue Number: #536 
Added up a simple project that is of Drum kit .
Project descriptive page :
=> data: project addition by abhay-raj19  #536

src/DB/projects.json
fixed issue #614 
added a new project to the list which is an online food-ordering web app, it is a Web application. 
Named Cosmic Cravings.
=> data: project addition by [poojaramnaney] #614

src/DB/projects.json
#829 
Added cryptospy project to the list
=> data: project addition by Manoj Sai #829

src/DB/projects.json
Issue number- #784 
Added a new project.
Project Name - HarryPotter website
Functionality - People can download HarryPotter books and movies for free. 
Kindly consider this PR under GSSoC 23.
=> data: project addition by anirudhsalaria #784

src/DB/projects.json
=> added new projects

src/DB/projects.json
Issue #812 
This pull request addresses issue #812. As a contributor for GSSoC '23, I kindly request the repository maintainers to review and merge the pull request. Your attention and assistance in resolving this matter are greatly appreciated.
Thank you.
=> data: project addition by suravshrestha #812

src/DB/projects.json
#524 
Hey @priyankarpal , I have added the yoga project to your website. Please review my pr and merge it. Thank you!
=> data: project addition by sumitkr2000 #524

src/DB/projects.json
Closes #817 
I have Added Binary search tree visualizer web based app.
This is a web-based application to visualize binary search tree operations. The user can insert a value to the binary search tree, find a value, delete a value, and traverse the tree using different traversal techniques. The application animates the binary search tree operations step by step in real-time to help users understand how the algorithm works.
=> Added project: Binary Search Tree Visualizer

src/App.jsx, src/utils/Loader.jsx
This pull request adds a lazy loading feature to the project. This feature will allow users to load data only when they need it, which can improve performance and reduce bandwidth usage. The lazy loading feature is implemented using the circular suspense loading pattern. This pattern allows the data to be loaded in the background while the user is still interacting with the page. This can provide a better user experience, as the user does not have to wait for the data to load before they can start using the page.
Issue
https://github.com/priyankarpal/ProjectsHut/issues/495
=> Lazy loading enabled and loader component added

README.md
=> Update README.md (#895)

src/components/ProjectList.jsx
Issue number : #898 
Changed the back to project path to "/projects".
=> Bug fix: changed Back to project Path

src/DB/projects.json
AR Watches project added.
#608 issue solved.
AR Watches project added.
=> data: project addition by TusharMinche #608

src/DB/projects.json
=>Added Project
Added a project to projects.json file
=> data: project addition by [abhrajitray77] #557

src/DB/projects.json
Issue number #612
Added a web3 project
=> data: project addition by [Google-Ka-Dinosaur] #612

src/DB/projects.json
=> Wajeeha codes patch 1

src/DB/projects.json
Added a project MovieApp  built with React, leveraging APIs to provide users with an extensive collection of movies and comprehensive search options.
=> data: project addition by @shagunZ #899

package.json, pnpm-lock.yaml, src/DB/projects.json, src/components/ScrollToTop.jsx, src/pages/HomePage.jsx, src/pages/ProjectsPage.jsx, src/utils/searchProject.js
Issue No: #400 
Add search-based project
=> feat: add search project option 

src/DB/projects.json
Closes :  #814 
Added three projects :
1. Sober-sense
2. Image-classifier
3. RoomRevamp
- I am a GSSoC Contributor !
=> addition of projects by ujjawaltyagii

src/DB/projects.json
Issue No: #695 
Added a python based machine learning project on Credit Card Fraud Detection.
=> data: project addition by [coderhersh] #695

src/DB/projects.json, src/pages/HomePage.jsx, tailwind.config.cjs
https://github.com/priyankarpal/ProjectsHut/assets/101205226/c3cb9f99-5632-4868-92df-c8cabe648d17
=> Modify HomePage.jsx

src/DB/projects.json
update project
issue number: #927
=> data: projects addition by akshaya #927

src/DB/projects.json
Added Project Med.Ez(Medicine management system).
Issue No #955 
Under #gssoc23
=> data: project addition Med.Ez(Medicine management system)

src/components/Footer.jsx
* Resolves issue - #970 
In the footer section, the tag says "All right reserved".
Changes it to - "All rights reserved".
=> Update Footer.jsx typo

src/pages/AddYourProjectsGuide.jsx
Fixed the docs page bug.
I'm in GSSOC'23.
=> Fix docs page bug #946

src/DB/projects.json
=> data: project addition by Utkers-h #916

src/DB/projects.json
=> data: project addition by prasanta10 #885

src/DB/projects.json
=> data: project addition by Monishka8303 #626

src/DB/projects.json
=> Data: project addition by using HTML ans CSS #706

src/DB/projects.json
=> Data: project addition by sonam #708

src/DB/projects.json
Issue_Number : #707 
Developed a chat based portfolio page that displays education, skills, projects, and resume (pdf) version 
from repository based on the word user types in a dynamic chat window. Used technologies like HTML, 
Javascript, and CSS.
=> Data: project addition by SJ-Kumar #707

CODE_OF_CONDUCT.md
=> Docs: Update CODE_OF_CONDUCT.md

src/DB/projects.json
This is issue number #981 
Adde new project of Google keeper clone using ReactJs
=> Data: project addition by Deepanshu #981

README.md, src/CSS/index.css, src/pages/AddYourProjectsGuide.jsx
From the issue #880  we have the information that its not  responsive on small devices  hence I have just fixed this issue using media screen 
Now for small devices its works perfectively 
Event smaller devices
=> Fix:  Improve responsiveness of page #880

src/DB/projects.json
Issue No: #1014
Its a Job Portal Website Made using MERN Stack Where we can See new jobs and add jobs
=> Data: project addition by pankajktech #1014

pnpm-lock.yaml, src/components/ProjectList.jsx, src/utils/paginate.js
Issue No: #922
add the feature which will show random project selection on every refresh
1st refresh:
2nd refresh
3rd Refresh
=> Feat: random project select

src/components/ProjectList.jsx
This PR closes issue #867 
Please review this PR.
Thanks
=> Fix: social media icons positioned properly inside the profile card #867

src/DB/projects.json
Added a new project movie recommender system
Closes the issue number #555 
A movie recommender system is a type of algorithmic software that provides personalized recommendations of movies to users based on their viewing history, preferences, and behavior.
=> data: projects added by Abhinav kumar

src/DB/projects.json
added a project of Razorpay clone
Issue number- #1063
A project made with Tailwind CSS and HTML, which is a front-end clone of the Razorpay payment gateway.
=> data: project addition by Jranii #1063

src/DB/projects.json, src/pages/AddYourProjectsGuide.jsx
[UI Improvement] - Revamping the Docs page #998 
The SVG on the docs page needed a slight change in opacity.
=> fix: change in the opacity of SVG on docs page

README.md
Fixes #1069 
I have changed this:
> Wanna see our the contributors ? (then click on below dropdown)
to:
> Wanna see our contributors? (then click on below dropdown)
This PR is part of GSSoC'23.
=> docs: Fix Text in README

src/DB/projects.json
- Added social links and updated projects link.
=> chore: update social and project links

src/DB/projects.json
=> chore: Added Projects

src/DB/projects.json
#592 
is your birthday lucky project added 
An App build with html css and Javascript. that calculate your Birthday is Lucky or Not
=> chore: project addition by Gurnav224  #592

src/pages/ProjectsPage.jsx
=> refactor: use search params to search

pnpm-lock.yaml, src/pages/HomePage.jsx
#1084 
This pull request addresses the issue where clicking on the logo in the footer redirects users to the homepage but displays the footer instead of the top of the page. The fix ensures that when users click on the logo, they are properly redirected to the top of the homepage, providing a seamless and consistent user experience.
https://github.com/priyankarpal/ProjectsHut/assets/103263909/79dd96d1-9efa-4e58-ae64-99c9ac696d94
=> fix:  Fix Logo Redirect in Footer to Top of Homepage

contributing.md, src/DB/projects.json
closes #1085 
This is web based Sudoku Game. It has:-
- Sudoku board generator that creates a unique puzzle every time
- Ability to input numbers and track progress
- Timer to track how long it takes to complete the puzzle
- Check functionality to see if current solution is correct
- Reset button to clear the board and start over
=> data: project addition by roshan798 #1085

.github/pr-title-checker-config.json, package.json, pnpm-lock.yaml, src/DB/projects.json, src/components/ProjectCard.jsx, src/components/ProjectLoading.jsx, src/components/SideMenu.jsx, src/pages/ProjectsPage.jsx, src/utils/searchProject.js
=> feat(Infinite Scrolling)

src/DB/projects.json
#1106 
Please include my projects in ProjectHut, Thank you.
=> chore: project addition by Saurav-Pant #1106

package.json, pnpm-lock.yaml, src/DB/projects.json, src/pages/AddYourProjectsGuide.jsx
=> fix: dispaly command is vs code format 

src/DB/projects.json
closes https://github.com/priyankarpal/ProjectsHut/issues/1104
I have provided a brief overview of the two methods for sending emails using Python. The first approach enables sending a single email, while the second approach extends this functionality by allowing bulk email sending through the use of a CSV file.
=> chore: project addition by BALASARVAN12 #1104

src/DB/projects.json, src/components/ScrollToTop.jsx
=> fix: #1044

src/DB/projects.json
#1138 
Description
I have followed the rules mentioned in contributing.md and made the PR . Drag and Drop clone project is made up of html ,css, js.
=> chore: project addition by Deepanshu #1138

package.json, pnpm-lock.yaml, src/DB/projects.json, src/components/ProjectList.jsx, src/components/ScrollToTop.jsx, src/pages/ProjectsPage.jsx, src/utils/paginate.js
Issue No: #1131
1. Solve the click issue on the profile page
2. Add pointer on the share profile link button
3. Add random project show on the projects page
=> fix: solve multiple errors

src/DB/projects.json
This pull request is regarding the issue number #1099 that I've raised earlier.
I have added an angular project called Pinax
=> chore: project addition by coderhersh #1099

src/DB/projects.json
#1144 
I added flutter voice assistant project which resolve doubts and question by asking in speech and it'll provide answer in text with voice.
=> chore: project addition by Jigar #1144

src/DB/homepage-image.json
Issue Number: #1075
FIXED: Site is taking a lot of time to load because of high-res images
=> fix: Site is taking a lot of time to load because of high-res images #1075

src/DB/projects.json
Issue number -#1149
Added a new project.
Project Name- TextGo
Functionality- You can perform multiple operations on your text.
Kindly consider this PR under GSSoC 23
=> data: project addition by anirudhsalaria #1149

src/DB/projects.json
Issue No. #1146 
I am GSSOC contributor. 
Added Certificated Generator
=> chore: added new project

src/DB/projects.json
I have added three of my projects mentioned below:
- [Movie Rental and Buying System](https://github.com/HartzFrequency/Movie_Rental_And_Buying_System)
- [Wave](https://github.com/HartzFrequency/Wave)
- [Unified Travelling and Transport System](https://github.com/HartzFrequency/Unified-Travelling-and-Transport-System)
Here are a few screenshots from each projects
=> chore: project addition by HartzFrequency #issue_number_1155 

src/DB/projects.json
project addition by @Ajay-Dhangar  #1166
https://github.com/priyankarpal/ProjectsHut/issues/1166
This project allows users to enter a GitHub username and view the profile information of the corresponding user. The project utilizes the GitHub API to fetch data such as the user's profile image, name, bio, website link, location, followers, following, and public repositories. The fetched data is then displayed in a visually appealing format on the web page. This project serves as a simple and interactive way to explore GitHub profiles and learn more about users and their contributions. The project is implemented using HTML, CSS, and JavaScript and can be easily deployed.
=> chore: project addition by Ajay-Dhangar #1166

src/DB/projects.json
https://github.com/priyankarpal/ProjectsHut/issues/1129
Add Jobby App Project
=> data: add project of swethapaleti

src/DB/projects.json
This pull request is with reference to issue number #1169
Weather app made with React JS and Tailwind CSS which uses OpenWeatherMap api to fetch the results.
https://github.com/priyankarpal/ProjectsHut/assets/56130865/df1ec926-8cf0-4cd1-a249-7e075a1b2926
=> chore: project addition by coderhersh issue number #1169

src/DB/projects.json
https://github.com/priyankarpal/ProjectsHut/issues/1181
- Encipher | Decipher is a simple encryption/decryption website which allows users to encrypt and decrypt messages using three cryptographic ciphers with a key
- Users are required to encrypt the message with a key, and in order to decrypt the same message, the former key should be used at the decryption section
- This website is highly responsive and it is built using HTML, CSS and JavaScript
=> chore: project addition by siddarthdayala #1181

src/pages/ProjectsPage.jsx
Issue No #1190 
Added text color black for light mode
=> feat(fix issue #1190): add text color black for light mode

src/DB/projects.json
This pull request is with reference to issue number #1198 
This repository consists of a To-Do List in which the backend is integrated using PHP.
=> chore: project addition by Atharvashirsh issue number #1198

src/DB/projects.json
This closes #1199
I have added one of my project "MESSI MANIA" into the projects section
=> chore: project addition by Soumyajit2825 #1199

src/DB/projects.json
#1221 
I have added a water tracker web application to count the daily water intake.
=> chore: project addition 

src/DB/projects.json
This pull request is with reference to issue number #1229 
This repo consists of a simple Dinosaur game made in Python using Pygame module.
=> chore: project addition by Atharvashirsh #1229

src/DB/projects.json
**resolves : #1216** 
Added the frontend part of an e-commerce website called shopzy. 
Tech stacks used: **ReactJs** and **TailwindCss**
=> chore: project addition by kirtiraj22 #1216

src/DB/projects.json
Build on HTML, CSS and JS based weather website that can fetch the real time weather of anywhere.
Added Weather website, raised under issue number: **#1225** 
Used JavaScript fetch method to get the responses from weather api, and CSS for responsive UI design.
=> chore: project addition by Prashu-01 #1225

src/DB/projects.json
Issue No - #1201
A Discord Bot for Coders. Now Contests and Hackathons related Information under your command. Executes Code in Discord Itself. Provides Jokes, News, Quotes and fun things. Supported - C, C++, Python, Java, JavaScript, Golang, C# etc.
=> chore:  Added Discord Bot Project

src/DB/projects.json
PR No. - #1244
Weather Forecasting Website
=> chore: project addition by Ajay84sia #1244

src/DB/projects.json
=> chore: update social links

src/DB/projects.json
PR No. #1251
issue number #1254 
Added new projects
=> chore: project addition by Ajay84sia #1251

src/DB/projects.json
added a new project plus add the link to the previous project and updated it
Issue #1232 
Added a new project plus updated the previous project link
=> chore: project addition by AmanSingh6574 #1232

src/DB/projects.json
Issue #1264
Added a game which is quickly and easily access a thrilling dungeon-crawling experience at any time. With a simple click of a button, players can enter a fully-realized, randomly generated dungeon filled with monsters and diablo inspired equipment looting system!
=> chore: project addition by Killer2OP #1264

src/DB/projects.json
This pull request is with reference to issue number #1252 
This PR is a User Database Management build using ExpressJS and MongoDB
=> chore: project addition by Atharvashirsh #1252

src/DB/projects.json
This pull request is with reference to issue number #1286 
A simple Xylophone App made in Flutter
=> chore: project addition by Atharvashirsh #1286

src/DB/projects.json
Unit converter Added
Issue no #1241
=> chore: project addition added Unit Converter

src/DB/projects.json
ADD TEXTUTILS (ISSUE #1261)
Added TextUtility React APP as suggested in contribution.md
=> chore: TextUtils ADD

src/DB/projects.json
#1266 
pet store is a e-commerce website for adopting pets
=> chore: project addition/added pet store by @mandliyarajendra11 ( #1266)

src/DB/projects.json
#1255 
I've added a new project called "Meme Generator," which allows users to easily create memes by adding top and bottom text to the top 100 trending memes.
=> chore: project addition/added Meme Generator (#1255)

package.json, pnpm-lock.yaml, src/DB/projects.json
Hello @priyankarpal ,
Added 5 Projects which is have mentioned in the Issue No. #1328 
[Screencast from 22-06-23 06:39:49 PM IST.webm](https://github.com/priyankarpal/ProjectsHut/assets/121503426/3dee4f65-7dbd-4554-91f6-5f5dbf84bf52)
=> chore: Adding 5 Projects 

src/DB/projects.json
Solves issue #1321 
The repository contains terminal games in Python such as Tic, Tac, Toe, Hangman etc.
=> chore: project addition by srujana-16 #1321

src/DB/projects.json
Adding MyOnlineMeal, an online food delivery web application, using ReactJS and JavaScript. Implemented intuitive user interfaces and interactive features to enhance the user experience. Utilized ReactJS components and libraries to efficiently manage and display food menus, order processing, and payment transactions.
New Project:Online Food App by junaid-arif-24 #1258
added a new project in the projects.json file
=> chore: project addition by [junaid-arif-24] #1258

src/DB/projects.json
#1265 
The goal of the application is to provide users with random pieces of advice to help them make better decisions in their personal and professional lives.
=> chore: project addition/added Advice Generator

src/DB/projects.json
#1259 
this is project is related to scrapping news from online articles
=> chore: project addition by [mswat5] #1259

src/DB/projects.json
close #1302 
This project is for generating the daily random quote. With each click new quote appear.
=> chore: project addition by aakanksha

src/DB/projects.json
Added Simon Game to ProjectsHut Repository + Resolve a Bug in 'React-Quiz' Project
Kindly Review the PR
Thank You!
Resolved 2 Issues :-
1. Project Addition #1269
2. Fixed Bug #1270 
Added Simon game, which is a short-term memory skill game.
Resolved the bug (react-quiz links to 404 error page), now added proper link to it which opens the game perfectly!
=> chore: project addition by sabhisharma-ise #1269

src/DB/projects.json
ISSUE #1289 
The problem has been resolved.
---
=> fix: Project under Wrong username #1289

src/DB/projects.json
closes #1346 
Navbar project using React addition
=> chore: project addition by MisterMickey #1346

src/DB/projects.json
Hello @priyankarpal ,
It is a IT Solution website for the Students which are in the final year and those who need projects. 👍🏻 
---
=> chore: Added IT Service Web-App

src/DB/projects.json
#1313 
I have just added my Project in the project.json file
---
=> chore: project addition by Hemant2335 #1313

src/DB/projects.json
Hello @priyankarpal ,
I have added the Java DSA Project for Students. 
-
Arrays
String
Matrix
Binary Search
Linear Search
nth Queen Algorithm
etc.
1.
2.
---
=> chore: Added Java Project

src/DB/projects.json
Issue number - 1345
close issue #1345 
- This game is multiplayer game
- 🕹️ Shuffling of 25 numbers 🎮
- 🎮 Initializing scores at start of the game and score calculation after every "hit" 🕹️
- 🕹️ Comparing and checking letters of "B I N G O" on each and every clicked 🎮
- 🎮 At the end of the game, declaring, either winner of the game or draw of the game 🕹️
- 🕹️ Also adding background sound in the background of the game, while playing 🎮
- 🎮 Providing support for the multi-players upto 10 🕹️
---
=> chore: project addition by Avdhesh-Varshney #1345

DB/projects.json, app/docs/page.tsx, app/index.ts, app/page.tsx, app/projects/page.tsx, components/Layout.tsx, components/Navbar.tsx, components/ProjectCard.tsx, components/ProjectList.tsx, components/SideMenu.tsx, context/FilterContext.tsx, context/Theme.tsx, next.config.js, package.json, pnpm-lock.yaml, utils/paginate.ts, utils/test-utils.tsx
=> fix: errors in project

src/DB/projects.json
#1395 
Hey @priyankarpal I have added the shades project to your repo. Please review my pr and merge it.
---
=> chore: project addition by sumitkr2000 #1395

src/DB/projects.json
added project
#1290 
added a project
---
=> chore: project addition by AmanSingh6574 #1290

src/DB/projects.json
=> chore: project addition by krutikajichkar

src/DB/projects.json
#1324 
Added Caesar and cipher project
---
=> chore: project addition by whiteknight16] #1324

src/DB/projects.json
Issue Number - 1443
close issue - #1443 
- 🎮 It is a multiplayer game 🕹️
- 🎮 This game is built to develop strategic thinking along with recreation 🕹️
- 🎮 This project is built on a basic web tech stacks such as HTML, CSS and Javascript 🕹️
- 🎮 Based on the lines connected, the boxes would be coloured 🕹️
- 🎮 The one with maximum number of boxes would be the winner 🕹️
I want to add this project under GSSoC'23 program.
---
=> chore: project addition by Avdhesh-Varshney #1443

src/DB/projects.json
Issue #1484 
The project is a to-do list that lists your submitted tasks and allows you to delete them once the tasks are completed.
---
=> chore: project addition by Rehan  (Issue  #1484)

src/DB/projects.json
closes #1462 
News App is a inshort clone by using Api, In this App I use a Gui with help of tkinter library
---
=> chore: Adding News App

src/DB/projects.json
Issue number of my PR is #1455
---
=> chore: project addition by Shivam #1455

src/DB/projects.json
#1436 
Added a new project to the list
- [ x] My project has contribution guidelines.
- [x ] My project has a Code of Conduct.
- [ x] My project has a README file.
- [x ] My project has a License.
---
=> chore: project addition by smty2018 

src/DB/projects.json
#1460 
Dance website added
---
=> chore: project addition added by Dance Website

src/DB/projects.json
#1435 
Cookie clicker bot that plays cookie clicker game
---
=> chore: Addition of cookie clicker whiteknight16

src/DB/projects.json
I have added my projects from my GitHub Account.
=> chore: Add Projects by Adity2911

src/DB/projects.json
#1472 
Added my Amazon clone project 
{
"link": "https://github.com/Prajwal0225/Amazon-Clone",
"title": "Amazon Clone",
"description": "Amazon clone with card functionality using strip",
"tech": ["HTML", "CSS", "JavaScript", "React", "Firebase"]
}
---
=> chore: Added by Amazon clone project

src/DB/projects.json
I've added new project to the list, which is API based project.
#1513 
---
=> chore: Added new project to the list

src/DB/projects.json
Added new Simon game project.
#1515 
I've added new project of Simon Game to the list where users can play and have fun !
---
=> chore: project added by AdityaLahane-2003

src/DB/projects.json
Close #1523 
In this project, an automatic obstacle detecting car was made. The car uses ultrasonic sensors to detect obstacles and avoid them. Color sensor is used to start and stop the car. An algorithm for the navigation of the car was created and implemented on the Arduino.
---
=> chore: project addition by srujana-16

src/DB/projects.json
#1490 
This project is used to show current weather conditions of the location entered by the user along with map of that location
---
=> chore: project added weather report

DB/projects.json
#1534 
In this project user can donate amount as per their capability using razorpay and that amount will be used for the welfare work
=> chore: project added donation carnival

components/SideMenu.tsx
#1521 
Added my Tesla clone project 
{
"link": "https://github.com/Prajwal0225/Tesla-clone",
"title": "Tesla Clone",
"description": "Tesla website clone with animation",
"tech": ["HTML", "CSS", "JavaScript", "React"]
}
=> chore: Added project by Prajwal0225

DB/projects.json
#1564
It displays a new page with a visually engaging background image of nature and displaying motivational quotes. This helps to create a more pleasant and inspiring environment for users when they open a new tab.
=> chore: project added motivational quote 

DB/projects.json
Issue Number - 1511
close issue #1511 
- Project which can convert the entered number into the international system of numbering.
I want to add this project under GSSoC'23 program
=> chore: project addition by Avdhesh-Varshney #1511

DB/projects.json
Closes #1452 
a customizable countdown timer using python.
=> chore: project addition by smty2018 #1452

DB/projects.json
Issue Number - 1549
close issue:-  #1549 
The project is a product landing page designed for an e-commerce website focused on headphones.
=> chore: project addition by Dimple-Choudhary #1549

DB/projects.json
Closes issue #1505 
I have added the student database management system project. Please review it and if it is fine then please merge it to the main branch.
=> chore: Added the Student Database Management system by Parmesh Bhatt

DB/projects.json
Closes #1480 
Added the UI design of a cat purchasing website
=> chore: added a project

README.md
=> docs: change the image

DB/projects.json
#1594
- Project Description:
`CoinMeter` is a completely responsive and functional real-time Cryptocurrency data fetching app. This app gives you the facility to analyze the top cryptocurrencies across the world and see their real-time market cap and exchanges with the help of a properly designed historical chart for each coin with a clean UI experience.It also has a trending section where the last 24 hours profitable coins are shown.
=> chore: project addition by Suraj Pratap : CoinMeter

.github/ISSUE_TEMPLATE/feature.yml
=> chore: Update feature.yml title

DB/projects.json
#1576 
This pull request aims to add the Laugh Hub project to Project Hut, a platform that hosts various innovative and entertaining projects. Laugh Hub is a delightful bot with advanced AI voice assistance, offering a wide range of fun features, including engaging conversations, hilarious stories, a meme generator, and entertaining games. This addition will provide users with a much-needed break from their daily routines by bringing laughter and amusement to their lives.
**Changes Made:**
1. Added the Laugh Hub project details to the `DB/projects.json` file, including the project name, description, features, and relevant metadata.
2. Ensured that the Laugh Hub project details adhere to the existing JSON structure and formatting conventions of the `projects.json` file.
=> chore: Add Laugh Hub Project to Project Hut

DB/demo.json, app/projects/page.tsx, components/api/fetchData.ts
Issue No: #1562
data fetch from github
=> feat: fetch data from github #1562

DB/projects.json
#1582 
Audio Book: Enter the pdf of book that you want to read and enjoy the audio book
=> chore: project addition by whiteknight16

DB/projects.json
=> chore: Added  AI Fusion project

components/Navbar.tsx
Issue Number: #1635 
The links which are currently active will be highlighted in primary color.
=> fix: modify the colour of active links in the navigation bar

DB/projects.json
Added Projects
#1649 
Added Project as previous one had some conflicts
=> chore: project addition by SurajG20 #1649

README.md
=> docs: remove a line

components/ProjectCard.tsx
user profile card css issue #1613
=> fix: css card issue #1613

DB/projects.json
#1672 
CodePen is an online community for testing and showcasing user-created HTML, CSS, and JavaScript code snippets. It functions as an online code editor and open-source learning environment, where developers can create code snippets, called "pens," and test them.
=> chore: project addition by Bhumica #1672

DB/projects.json
#1679 
Added Temperature Converter
=> chore: project addition by blindaks #1679

DB/projects.json
#1624 
This pull request aims to add the Contentify project to Project Hut,Contentify is a versatile content creation, social media management, and educational resources platform. It provides users with a comprehensive set of tools to excel in content creation, streamline social media management, and access valuable educational resources.
**Changes Made:**
1. Added the Contentify project details to the `DB/projects.json` file, including the project name, description, features, and relevant metadata.
2. Ensured that the Contentify project details adhere to the existing JSON structure and formatting conventions of the `projects.json` file.
=> chore: Project addition by Nishit Baria ✔

DB/projects.json
#1683 
Added a TO-DO LIST. This project is a to-do list where users can add new items in different lists and strike out them to mark them as completed. It is easy to use. Fully responsive.
New item added
New list
=> chore: project addition by Bhumica #1683

components/Footer.tsx
=> fix: update footer

server/.gitignore, server/package.json, server/server.ts, server/src/projects/projects.router.ts, server/src/projects/projects.service.ts, server/tsconfig.json
=> feat: add server

server/src/user/user.router.ts, server/src/user/user.service.ts
=> feat: added User service

DB/projects.json
=> chore: added Harsh to projects #1652

DB/projects.json
=> chore: added sahil chalke to projects #1729

DB/projects.json
#1722 
Vanilla JavaScript Project.
=> chore: Added Testimonial Project

DB/projects.json, pnpm-lock.yaml, server/package.json, server/src/projects/project.interface.ts, server/src/projects/projects.router.ts, server/src/projects/projects.service.ts, server/src/user/user.interface.ts, server/src/user/user.router.ts, server/src/user/user.service.ts
=> feat: server type defination

app/docs/page.tsx, app/layout.tsx, app/page.tsx, app/projects/[username]/page.tsx, app/projects/page.tsx, components/Navbar.tsx
=> fix: Added `Navbar` Component in the layout.

components/Footer.tsx
Related Issue
Closes #1732 
Description:-
Changed the hover text color from text-grey-200 to text-primary on line 87 in `components/Footer.tsx` to make it more professional.
Screenshots
Earlier:
Updated:
Please review and merge the changes.
=> fix: hover effect is added to social media links

DB/projects.json
#1721
Color Flipper Vanilla JavaScript Project.
=> chore: added color flipper project (vaibhav-xt)

utils/techStack.ts
Closes #1735 
Title: Addition of Express and Firebase to Filters
Description
This pull request adds Express and Firebase to the existing list of technologies in the utils/techStack.ts file. The techStack array now includes the following technologies:
const techStack = [
"reactjs",
"nodejs",
"nextjs",
"javaScript",
"python",
"mongodb",
"typescript",
"express",
"firebase"
];
Please review and merge this pull request to incorporate these changes into the project.
Screenshots:-
earlier:-
updated:-
=> fix: Added firebase and express to filters

components/Footer.tsx
=> fix: Footer text color

DB/projects.json
This PR closes issue no. #1754 (project addition by palakkgoyal)
I added a new project in which techstacks used include React and Tailwind.
=> chore: project addition by [palakkgoyal] #1754

components/Footer.tsx
- Added aria label on footer social icons
=> fix: Added aria label on social icons

DB/projects.json
This PR closes issue no. #1757 (project addition by anshul soni)
added music player webpage which is just like spotify where you can play your songs
=> chore: project addition by [anshulsoni4] #1757

README.md
Resolves
#1763  
Added a contributors section with a toggle button.
=> fix: Added Contributors Section

pnpm-lock.yaml, server/.gitignore, server/package.json, server/server.ts, server/src/projects/project.interface.ts, server/src/schema/Projects/project.schema.ts, server/src/schema/User/user.schema.ts, server/src/schema/mongo.connect.ts
=> feat: add database

DB/projects.json
this pr closes issue no #1728 .
this is a portfolio website which cann give idea about design using only html and css.
=> chore: project addition by [ankit-0369] #1728

pnpm-lock.yaml, server/package.json, server/server.ts, server/src/projects/project.interface.ts, server/src/projects/projects.router.ts, server/src/projects/projects.service.ts, server/src/user/user.router.ts, server/src/user/user.service.ts, server/src/validations/project.validation.ts, server/src/validations/user.validation.ts
=> feat: add validation

components/Footer.tsx
#1779 Add logo
I am adding logo in footer and also increase size of heading.
=> feat: add logo in footer

DB/projects.json
- A Cloud Reminder Application
- A Wildfire Saviour Application
- A Super Chat Application
Closes #1805
=> chore: project addition by ighoshsubho #1805

DB/projects.json
Clears issue #1789 
Added a crypto currency project
=> chore: Added crypto project

DB/projects.json
=> chore: Added travel site project

components/Footer.tsx
#1802 Icon Hover
Hover effect has been added accordingly to their social media
=> fix: added icon hover for social platforms

DB/projects.json
I have Added React-Native Project as I describe in issue #1828 
I am sharing video of that project UI
https://github.com/priyankarpal/ProjectsHut/assets/89975347/2c110592-4fb3-4bc7-ab27-2d95b1f9420e
=> chore: project addition by Harshu467 #1828

.husky/commit-msg, commitlint.config.ts, package.json, pnpm-lock.yaml
#1833 #1824
- Installed husky 
- Installed commit lint
=> chore: setup husky and commitlint

DB/projects.json, app/page.tsx
=> chore: IOT project added

DB/projects.json
Issue Number - 1626
close issue #1626 
This project can tell you about how much time has gone from the entered date and time even in milli-seconds.
=> chore: project addition by Avdhesh-Varshney #1626

app/projects/[username]/page.tsx
- In project file all the links have aria-label as github 
- I add proper aria-label in each links
=> fix: added proper aria-label in project folder

DB/projects.json
Added The project -- Grocery Website made by me using HTML, CSS, JS, SwiperJS. It has a modern design and is fully responsive.
=> chore: project addition by rishabhchaudhary0210 #1862

app/projects/page.tsx
#1876 
Added a close button to the filter dialog panel in the projects page.
=> feat: add close button to filter panel (#1876)

DB/projects.json
#1867
Added my forum-based and community-based social media website to the list of projects. The tech stack for the website is reactjs, javascript, nodejs, expressjs, mongodb, and mongoose.
=> chore: project addition by pewpewnor #1867

DB/projects.json
Regarding Issue Number #1869 
Added Machine Learning Project of water Quality Prediction
=> chore: project addition by Harshu467 #1869

app/projects/[username]/page.tsx, components/Footer.tsx, components/ProjectCard.tsx
Closes Issue No : #1878 
- **Added `aria-label and title attributes to respective Social Links  in app/projects/[username]/page.tsx -File`**
- **Added `title attributes to Respective Social Links a nd Modified aria-label  for Social Links to Improve Scalability and Clean Code of Same Content in components/Footer.tsx- File`**
-  **Added `title and aria-label attributes to GitHub Social Link in components/ProjectCard.tsx- File`**
=> fix: Updated and Modified title, aria-label for Social Links in Some Pages

app/page.tsx
Closes: #1874
Fixing the Home Page Width Exceeding Screen Width
=> fix: home page width overflow issue

components/Navbar.tsx
As mentioned in issue Number #1887 , active page should be purple and it was not.
I have fixed the issue , now when paage is active it will be shown in purple color. You can check out
=> chore: Navbar Inconsistencyfixed by Harshu467 #1887 

app/projects/[username]/page.tsx, components/Navbar.tsx
As mentioned in issue number #1884 about project Focus effect, Updated
I have updated design in profile section sharing sample
[Screencast from 30-07-23 11:25:57 AM IST.webm](https://github.com/priyankarpal/ProjectsHut/assets/89975347/6e2c6b1c-1448-4722-bb3d-c4968890dd53)
=> chore: Project focus updated by Harshu467 #1884

app/projects/page.tsx, components/ProjectCard.tsx, pnpm-lock.yaml
=> style: Animated Projects

DB/projects.json
#1842 
It is a space-themed website made using HTML, CSS and Bootstrap.
=> chore: Add space themed website

components/MobileNavbar.tsx
=> fix(bug): navbar spacing in phones

app/projects/[username]/page.tsx, components/Footer.tsx
Close #1896 
- Revamped the hover states of social icons from Individual colors to site's primary purple color.
https://github.com/priyankarpal/ProjectsHut/assets/92252895/065a287d-7056-41cf-9071-1538ae7cc1e8
=> feat: revamp hover states for social icons 🪄✨ 

DB/projects.json
Closes: #1913 
Refactoring all the teck-stack name to lowercase
=> refactor: lowercasing tech stack name

components/Navbar.tsx
- Applied glass morphism in Navbar
=> style: applied glass morphism in navbar

DB/projects.json
=> chore: project addition added by Ludo Game

DB/projects.json, components/Footer.tsx, components/MobileNavbar.tsx, components/Navbar.tsx, components/ScrollToTop.tsx, components/landing/Home.tsx, components/projects/ProjectCard.tsx, components/projects/ProjectList.tsx
Resolves #1943 
- convert anchor tag to `<Link>` 
- add `aria-label` to links & buttons
=> chore: use Link component and add aria-label

components/Footer.tsx
Closes: #1944 
Decreasing font size and applying Pascal casing to `projectshut` of copyright section.
=> style: decresing font-size of copyright section

DB/projects.json
Closes issue #1938 
I have added a new ML project Fake-News-Detection.
=> chore: added new ML Project by Parul1606 #1938

DB/projects.json
Closes #1958 
Added project of speech-to-text.
The Speech-to-Text system is a powerful tool that allows you to convert spoken language into written text.
=> chore: project addition by pavitrachavda97 #1958

.gitignore, DB/projects.json, components/Footer.tsx, contributing.md, package.json, pnpm-lock.yaml
=> fix: conflict solved

DB/projects.json
Closes #1959 
Three projects added
1) Background-creator
2) Whack-a-mole
3) Shipment-booking
=> chore: project addition by pavitrachavda97 #1959

DB/projects.json
Added 2 Great and Usefull Projects :
1. Euphoria-Check : A Modern PERMA meter to check PERMA scores( Positive Engagement Meaning Relationships Meaning Accomplishment) inspired from Happiness Research  Built in Express JS, NodeJs, Safely Secured using SendGrid API for Personalised Emails with Quotes and Scores
2. Email Subscription Web App: A Web App that lets users subscribe for a newsletter or emails built using Mailchimp API , ExpressJS, NodeJS
Please merge this,
Thanks Aryan Inguz
=> chore: projects addition by aryainguz #1974

components/projects/ProjectList.tsx
Closes #1975
This pull request makes some changes to the `ProjectsList.tsx` file to improve the appearance of the projects page. Specifically, I added the `md:top-28` CSS class to adjust the positioning of elements, which resulted in a better-looking page layout.
- Modified `ProjectsList.tsx` to include the `md:top-28` CSS class.
The ProfileCard stays fixed:-
=> style: fixed the profile-card moving issue

app/layout.tsx
Closes: #1983 
Resolving warning getting in terminal
=> chore: adding metadatabase

DB/projects.json
Closes issue https://github.com/priyankarpal/ProjectsHut/issues/2000
Adding an open source React PWA Starter template, built with Create-React-App, MUI and Firebase
=> chore: project addition by nc1z #2000

components/projects/ProjectList.tsx
Closes: #1994 
Improving Handling of Unidentified Dynamic Routes - Redirect to 404 Page
=> chore: handling unidentified dynamic routes

components/AddYourProjectsGuide.tsx, contributing.md
Closes: #1992 
updating site docs and contributing.md
=> docs: updating site docs and contributing.md

components/projects/ProjectCard.tsx
Closes: #1993 
Adding hover & click effect in projects card
=> fix: adding hover & click effect in projects card

components/AddYourProjectsGuide.tsx
Issue solved #1981 
- In this PR, I have added a new feature of the steps in the documentation part for more readability and consistency in the UI.
- And have also changed some background and text color in the UI.
- Also removed the arrow icons.
=> feat: added the steps feature in the docs with improvising the UI

components/projects/ProjectList.tsx
Closes: #2006 
Fixing Linking issue with external icon in dynamic project route
=> fix: fixing hyperlink issue

package.json, pnpm-lock.yaml
For #2005 
Installing sharp package
=> chore: installing sharp package

contributing.md
Fixes #2047
I have fixed the typo in CONTRIBUTING.md.
=> fix(docs): typo in CONTRIBUTING.md

components/AddYourProjectsGuide.tsx, components/framer-motion/index.tsx, components/framer-motion/util.tsx, components/landing/Banner.tsx, components/landing/Home.tsx, components/projects/ProjectCard.tsx, components/projects/Projects.tsx
Closes: #2045 
implementing use of framer-motion in server components for better SEO and faster page loads
=> feat: implementing use of framer-motion in server components

DB/projects.json
refactor: remove duplicate key & value #2050
=> refactor: remove duplicate key & value #2050

DB/projects.json, components/projects/ProjectCard.tsx, components/projects/ProjectList.tsx, components/projects/Projects.tsx
Closes: #2049 
updating "link" to "github_url" in JSON file `DB/projects.json`
=> refactor: updating "link" to "github_url" in JSON file

.github/ISSUE_TEMPLATE/bug.yml, .github/ISSUE_TEMPLATE/docs.yml, .github/ISSUE_TEMPLATE/feature.yml, .github/ISSUE_TEMPLATE/refactor_code.yml, .github/ISSUE_TEMPLATE/styles.yml, .github/workflows/issue-lock.yml
=> chore: remove gssoc checkboxes

DB/projects.json
=> chore: Mrittik-Server – an open-source REST API developed with Node.js and Express.js

utils/techStack.ts
feat: add Tailwind CSS to filters
Closes #2076
- Added Tailwind CSS styles to the filters.
- Made changes in utils/techStack.ts file.
- Included screenshots for preview.
Screenshots:
=> feat: added tailwind CSS to filters

.github/ISSUE_TEMPLATE/styles.yml
=> docs: update description of styles.yml

DB/projects.json
=> chore: project addition by RaviSolanki27

DB/projects.json
closes #2096 
Added an project in the DB/projects.json file
No ss
=> chore: project addition by sahilchalke

contributing.md
closes #2094
Created a short video providing an overview on how to make your first PR and added it to contributing.md
=> docs: added video guide to contributing.md

DB/projects.json
closes #2102 
Added a project in the DB/projects.json file
=> chore: project addition by ChiragAgg5k #2102

DB/projects.json
closes #2105 
Added a couple of projects in the DB/projects.json file
=> chore: project addition by MuhammadRabi  issue#2105

DB/projects.json
- Added my GitHub profile
- Added 2 of my projects and there details
=> chore: addition of profile uzumaki4303

DB/projects.json
closes #2114
Added a new project in DB/projects.json
No screenshots
=> chore: project addition by lorenzomiscoli #2114

utils/techStack.ts
closes #2116
Added angular to techStack
No screenshots
=> feat: add angular to techStack

components/projects/Projects.tsx
Filter clear button Issue 
Fiter clear button was visible whether there is any filter selected or not.
=> fix: resolve issue2125

components/Footer.tsx
closes #2127 
Changed the components/Footer.tsx file
replaced SiTwitter with SiX icon
=> style: changed the twitter logo

DB/projects.json
Closes issue #2143 
Added a personal portfolio website to DB/projects.json
=> chore: project addition by surya-mu #2143

DB/projects.json
I have added a new project in the db/projects.json
My Project is a web app, which is a clone of the IMDB website, made using reactjs , tailwindcss and for an API call I have used TMDB API
If you can add the hacktoberfest tag, I'll be grateful
and If there is an issue to which you think I can contribute, please assign it to me, I'll try to make some meaningful contributions
=> chore: project addition by trishit78 #2160

DB/projects.json
fixes: #2184
- added projectshut project
=> chore: project addition by priyankarpal

DB/projects.json
I have successfully added my projects.
=> chore: project addition by ayushrakesh #2201

DB/projects.json
Fixes #2180 
I've added my QR code scanner and generator WebApp
=> chore: project addition by singodiyashubham87

DB/projects.json
Added my project **HumorBlast** - the joke generator built using HTML, CSS and Javascript
Live project link - **https://vinay-s36.github.io/HumorBlast/**
=> chore: project addition by vinay-s36 #2204

DB/projects.json
Added 2 projects 
@priyankarpal 
fixed #2195
=> chore: project addition by kaushal1717

DB/projects.json
Closes #2191 
A website which tracks and provides details about the real time trend in crypto currency.
=> chore: project addition by Prakhar-Shankar

DB/projects.json
#2206 
chore: project addition by VinayKokate22 it is a ecommerce project made from scratch
=> chore: project addition by VinayKokate22

DB/projects.json
=> chore: project addition by vrundraval24 #2216

DB/projects.json
As mentioned in the issue #2211 , I am adding two projects to the repo Ping Pong and Sorting Visualizer
Merge my request after check @priyankarpal
=> chore: project addition by ayan-joshi 

DB/projects.json
#2207 
Added a simple quiz website based on front-end web development.
=> chore: Project Addition by blindaks

README.md
There were no issues for this. I identified this problem on my own.
I corrected the link to CODE_OF_CONDUCT.md in the README.md , the previous link was not a valid one
No screenshots needed, you can check the README.md
=> docs: addition of link to CODE_OF_CONDUCT.md in README.md

CODE_OF_CONDUCT.md
There are no existing issues for this, i just wanted to see the twitter of @priyankarpal  so i came across this issue.
This PR resolves the problem with the link provided for twitter account of @priyankarpal , it had a small typo and it was not redirecting to the correct page. (It was not a valid URL). I corrected it.
No screenshots required, you can check the CODE_OF_CONDUCT.md
=> docs: updated twitter link in CODE_OF_CONDUCT.md by [adarsh-jha-dev]

DB/projects.json
=> chore: add new projects to the list

DB/projects.json
- Added: https://devprofiles.is-an.app
=> chore: project addition by Priyansh

DB/projects.json
=> added introspecta

README.md
Typo update.
Issue no:- [https://github.com/priyankarpal/projectshut/issues/2345](2345)
Update of the issue (ss):-
=> chore: Typo error #2345

DB/projects.json
Added [digitomize](https://digitomize.com)
=> chore: project addition by pranshugupta54

DB/projects.json
=> chore: project addition by himanshuchandola

DB/projects.json
closes #2445 
Added a project in DB/projects.json file
no ss
=> chore: projects addition 

.github/dependabot.yml
=> chore: disable dependabot 😩😵

components/landing/Home.tsx
Fixes: #2482
The "Browser Projects" button in landing page contains border. But this button bottom border is not visible during smaller screens.
Before:
After:
=> fix: Landing page button borders

.github/workflows/broken-link-checker.yaml
fixes #2505
Add a github action to check for broken links
I would like to implement the second part which it supposed to open an issue if it finds broken links. 
I want able to do it in my repo due to permission issue. here is the code for this action:
```yml
- name: Create Issue From File
if: env.lychee_exit_code != 0
uses: peter-evans/create-issue-from-file@v5.0.0
with:
title: Link Checker Report
content-filepath: ./lychee/out.md
labels: Broken Link
```
=> feat: Add broken links checker, 

contributing.md
fixes #2513
delete broken link from contributing file
=> fix: Broken link in contributing.md

DB/projects.json, components/Footer.tsx
The issue occurred on the project page where the projects component implemented infinite scrolling, making the footer inaccessible. Previously, as soon as the footer was reached, new projects would load, continually pushing the footer out of view. Now, after adjusting the footer's height, this trigger has been deactivated, allowing the footer to be accessed.
GGsoc contribution
=> refactor: resolved unreachable footer issue

DB/projects.json
I'm opening this pr to add my project to Projectshut site.
=> chore: adding my projects to projectshut.

package.json, pnpm-lock.yaml
=> chore: lol

components/Footer.tsx
=> fix: center the footer text
