priyankarpal/projectshut

- src/components/SplashScreen.jsx
This PR fixes the text color issue on SplashScreen reported in [#272](https://github.com/priyankarpal/ProjectsHut/issues/272)
> fix: text color issue on splash screen #272

- src/components/SideMenu.jsx
#901 
Projects page link fixed in navbar
#901 
The link in sidemenu was referring to path /projectsPage but it does not exist .So changed it to projects
[scrnli_27_05_2023_20-11-34.webm](https://github.com/priyankarpal/ProjectsHut/assets/92094765/d65ac32e-967a-475e-83aa-734cc99b4f94)
> #901-fixed projects link in mobile

- .github/labeler.yaml
- .github/workflows/ph-labeler.yaml
- Fixes #931 
- Added Github Action for Labelling GSSoC PRs according to the level of contribution made
- Used the `labeler` GitHub Action for implementation
> Added Github Action for Labelling PR

- README.md
- Closes/Fixes: #1022 
- Added repository Contributors graph which shows an overall picture of all contributors who contributed to this project/repository
- Additionally we added a dropdown menu using `details` & `summary`, So that the Graph itself will not consume more space until we open it to see it
> Docs: add contributors graph with dropdown

- src/components/SideMenu.jsx
Closes : #1074 
- #### Added Project page path for small screens when nav-bar turns into side-menu resulting user to open project page on mobile screen using side-menu as well.
> fix: project page path error for side-menu

- src/DB/projects.json
- src/components/ProjectList.jsx
Issue #1136 
In this Pull Request, I solved these bugs that were occurring on large as well as small screen sizes
- Back to Projects button and share button were not aligned properly, So I aligned them for small and large screen sizes.
- The pop-up model does not position well on small screens, So I positioned it properly
- The project card gap was going out of bound
> fix: Optimized card, Popup and Project list

- src/DB/projects.json
#1141
This app provides a user-friendly interface and real-time score updates.  The app dynamically updates the scores in real-time, providing an interactive and engaging experience. The app incorporates a score limit feature and displays the winner when the score limit is reached.
> chore: project addition by shagunZ

- index.html
Closes #1215 
Added meta tags like title, open graph, twitter in the index file.
> feat: Meta tags added

- src/DB/projects.json
#1245 
Added two projects;
1. NFT Marketplace - A site to view nft tokens, prices and collections
2. JobWriteAi - A site to generate cover letters after pasting Job Descriptions
> chore: project addition by Judge-Paul #1245

- src/components/ProjectCard.jsx
#1248 
The improper alignments of "GitHub Link" and "More" button has been fixed
Before:
After:
> fix: Fix UI alignments for Project Cards

- src/DB/projects.json
@Akash-Tandale001 #1416 
Added Various Projects
---
> chore: project addition by Akash-Tandale001 #1416

- src/DB/projects.json
@Harshu467
#1334 
---
Ready to Merge
> chore: project addition by @Harshu467 #1334

- app/docs/page.tsx
#1517 
I have made the code easier to read and modular, based on the concept of DRY. This code is renders the exact same webpage as before, while also making it readable.
Lines of code halved from 427 to 261.
> refactor: Improved Docs Page Codebase

- README.md
- app/docs/page.tsx
#1519
I have added the button that partitions the two methods of showing how to contribute to the user.
> feat: Added Options Button in Docs page.

- app/docs/page.tsx
#1249 
Replaced the copy button text with a clipboard icon. On clicking the icon a green check will appear for 3 seconds indicating that the text has been copied
On clicking:
> fix: Replaced copy text with ClipBoard icon

- README.md
Closes #1631 
- This PR is about making the GSSoC Banner adaptable for Dark/Light Mode of Github.
- The banner will be swapped according to the theme preference, it uses Github's inbuilt functionality.
| WITHOUT USING GITHUB'S FEATURE |
| :--: |
| ![](https://github.com/priyankarpal/ProjectsHut/assets/92252895/2a358a0b-b1f7-454a-85eb-00c0ed7e7ce6) |
<br>
<div align=center>
**AFTER USING GITHUB'S FEATURE**
</div>
| DARK THEME | LIGHT THEME |
| :--: | :---: |
| ![](https://github.com/priyankarpal/ProjectsHut/assets/92252895/14255d1a-8b86-4115-9634-c6aeb352fb12) | ![](https://github.com/priyankarpal/ProjectsHut/assets/92252895/abee8768-ada5-4b54-a3aa-ec4831c79933) |
> docs: add dark/light theme adaptable gssoc banner 💡

- app/projects/page.tsx
clear button disable when there is no filter applied  bug no #1654
> fix: clear button disable when there is no filter applied #1654

- components/Navbar.tsx
Related issue: 
Closes #1670 
Updated Navbar component to open the GitHub link in a new tab
This pull request modifies the Navbar component to enhance user experience by opening the GitHub link in a new tab when clicked. Previously, the link would navigate within the same tab, causing users to leave the current website.
To achieve this, the following changes were made:
- Added the 'target="_blank"' attribute to the <a> tag wrapping the GitHub link.
- Introduced the 'external' property in the navLinks array to indicate an external link.
- Updated the rendering logic to conditionally render an <a> tag for external links with the appropriate attributes.
Now, when users click on the GitHub link in the navbar, it will open in a new tab, allowing them to easily navigate to the GitHub repository …
> fix: Opens Github link in new tab

- app/page.tsx
Related Issue
Closes #1741
Description
I made a change by adding a my-1 class to provide margin and avoid overlap. The change is currently working fine.
Screenshots
Earlier:
Updated:
Please find the revised statements below:
Changes Made
Added my-1 class to provide margin and avoid overlap.
Request for Review
Please review the changes and provide feedback.
> fix: Makes the Browse Projects button visible in mobile mode

- app/projects/[username]/page.tsx
- components/ProjectCard.tsx
Close #1762
- This PR is about fixing the improper pointer for the social icons on Users Profile.
- This Bug is fixed by adding `cursor-pointer` tailwind utility class so that we explicitly making the pointers actions same for all icons
https://github.com/priyankarpal/ProjectsHut/assets/92252895/3630f09f-6619-47b8-bd44-afffce33c7b2
> fix: improper pointer actions 🛠

- components/Banner.tsx
Close #1798 
- This PR is about fixing the space consuming border behavior for elements on intro page.
- We resolved it using `outline` property, it's a new one and best alternative for `border` property on css.
https://github.com/priyankarpal/ProjectsHut/assets/92252895/9d07ff09-4ee9-4bb6-a058-f328fcc84506
> fix: space consuming border for elements on intro page 🛠

- server/src/middleware/auth.ts
- server/src/projects/projects.service.ts
- server/src/user/user.service.ts
> feat: add authentication

- .github/ISSUE_TEMPLATE/bug.yml
- .github/ISSUE_TEMPLATE/docs.yml
- .github/ISSUE_TEMPLATE/feature.yml
- .github/ISSUE_TEMPLATE/project-add.yml
Closes #1813 
- Improve checklist with addition of three links with appropriate option
```yml
- label: I have checked the existing [issues](https://github.com/priyankarpal/ProjectsHut/issues)
required: true
- label: I have read the [Contributing Guidelines](https://github.com/priyankarpal/ProjectsHut/blob/main/contributing.md)
required: true
- label: I agree to follow this project's [Code of Conduct](https://github.com/priyankarpal/ProjectsHut/blob/main/CODE_OF_CONDUCT.md)
required: true
```
> chore: update checklist in all the issue forms

- .github/workflows/stale-issue.yml
> ci: change stale the issue & pr messages

- components/Footer.tsx
- components/MobileNavbar.tsx
Close #1801 
- Fixed the hidden copyright bug which occured for mobile devices with tailwind css responsive utility classes.
|BEFORE| AFTER |
| :---: | :---: |
| ![Screenshot_2023-07-22-15-27-44_1366x768](https://github.com/priyankarpal/ProjectsHut/assets/92252895/92689225-d6fe-4e58-972d-b40b065c9ee9) | ![image](https://github.com/priyankarpal/ProjectsHut/assets/92252895/4ef2ec6a-e590-4a87-b965-107c7c0613f5) |
> fix: hidden copyright for mobile devices 🛠

- app/page.tsx
Close #1797 
- Fixed the improper image floating animation on homepage by removing the animation class `floating-image` from `img`  and added that for the container `div` which holds the image.
https://github.com/priyankarpal/ProjectsHut/assets/92252895/d249b9c4-bb72-4898-bcc3-8db75beece33
> fix: improper image floating animation on homepage 🛠

- app/page.tsx
Close #1853 
|BEFORE|AFTER|
|:----:|:----:|
| ![before](https://user-images.githubusercontent.com/92252895/256201435-8d8a4f79-325a-44de-a04f-f16565b88d27.png) | ![after](https://github.com/priyankarpal/ProjectsHut/assets/92252895/f9c3a2ad-a712-4ab9-ba75-e5c8fdeb5b20) |
> fix: browse projects button cut-off on homepage for mobile devices 🛠

- app/page.tsx
Close #1855 
- Fixed the improper way of hiding images by removing the `overflow-hidden` from Section and disabled the images block with `hidden` and make sure to display them on tablets and above devices with `block` utility class.
> fix: improper way of hiding images on homepage 🛠

- app/layout.tsx
- Added proper meta tags to improve the SEO score
- Also properly added keywords , titles, description etc to improve SEO
> fix: Improved SEO

- app/projects/[username]/page.tsx
As Mention in #1829 issue, all icons given same hover color effect which was not standard, I have changed to proper color
I have changed hover effect color according to their application
> chore: added icon hover #1829

- app/page.tsx
- components/Banner.tsx
> chore: Prevent Text Selection

- components/Banner.tsx
- components/Navbar.tsx
As mentioned in issue  #1886 
Resolved
> chore: Why to use section by Harshu467 #1886

- .github/ISSUE_TEMPLATE/refactor_code.yml
- .github/workflows/stale-issue.yml
Closes #1900
- You need to add this label: `goal: refactor`
> chore: add refactor issue form

- DB/projects.json
Closes: #1928 
standordizing and lowercasing tech stack names
> refactor: standordizing and lowercasing tech stack names

- app/layout.tsx
Closes: #1930
Implementing Next.js Metadata API for better SEO and Web Shareability
> feat: Implementing Next.js Metadata API for better SEO and Web Shareability

- .github/ISSUE_TEMPLATE/styles.yml
- Fixes Issue No : #1924 
-  Added `styles.yml for GitHub ISSUE_TEMPLATES using for Raising Enhancement Requests.`
> fix: Updated styles.yml File For ISSUE TEMPLATES

- components/MobileNavbar.tsx
- components/Navbar.tsx
> style: make mobile navbar transparent #1934

- components/Footer.tsx
- components/landing/Banner.tsx
- components/landing/Home.tsx
Closes #1899 
- Mentioned in the Issue description (just styling update)
> chore: update styling of homepage on small devices

- components/Footer.tsx
Pull Request Title: Fix Footer alignment and documentation in components/Footer.tsx
Closes #1952 
Pull Request Description:
This pull request addresses the issue #1952 and includes the following changes in components/Footer.tsx:
Fixed the alignment of the footer to ensure it is visually consistent across different screen sizes.
Updated the documentation and license information in the footer to provide accurate and up-to-date details.
The screenshots below demonstrate the changes made:
Before:
After:
These changes enhance the user experience and ensure that the necessary information is correctly displayed in the footer. The PR is now ready for review and merging.
> style: aligned  documentation and license in footer

- components/Footer.tsx
Issue : #1810
This PR proposes an improved logo type for the ProjectHunt Project to enhance user engagement and encourage GitHub contributions. The updated logo prominently showcases "Start Contribution" ✨ at the top, followed by "Star on GitHub" 🤝 to prompt users to interact with the repository. Additionally, a dynamic element indicates the total number of stars the project has received, giving users a quick overview of its popularity 🌟.
Key Changes:
- **Responsive Design:** The logo is now responsive, ensuring a seamless experience across various screen sizes.
**Code Changes:**
```html
<div className="github-button p-2 bg-white rounded-lg max-w-[170px] mx-auto">
<a
className="github"
href="https://github.com/priyankarpal/ProjectsHut"
target="_blank"
rel="noreferrer"
>
<img …
```
> chore: Added `star on GitHub` image 🌟🚀

- components/Footer.tsx
- contributing.md
Closes Issue #1917 
As per the requirement, I have added two readme points."
> docs: improve contributing guide

- components/projects/ProjectList.tsx
Close #1970
- Refactored the `ProjectList.tsx` Component.
- Replaced Github icon with External Link icon.
- Implement hover feature for Cards and UI enhancements.
https://github.com/priyankarpal/ProjectsHut/assets/92252895/5d45ea96-32ff-4b25-ac9c-5664f2cf4ebb
> refactor: enhancing ProjectList.tsx 🪄 ✨ 

- components/Footer.tsx
Related Issue:-
Closes #1966
Description:-
Made changes in the Components/Footer.tsx file to improve the mobile view alignment. Added the text-center class to the <ul> element to center the content.
This change addresses issue #1966 by ensuring that the footer content is properly centered on mobile devices.
Screenshots:-
-
> style: made the footer in mobile view centered

- DB/projects.json
#1980 
chore: project addition by iqrasarwar #1980
> chore: project addition by iqrasarwar #1980

- DB/projects.json
- components/projects/ProjectList.tsx
Closes: #1982 
displaying social icons with valid social URL
- implemented logic to show the icons only when the string is not empty
- for GitHub, adding URL based on the collected GitHub username as some users are not adding GitHub account URL. 
|      Original       |      Updated       |
| :-----------------: | :----------------: |
| ![image](https://github.com/priyankarpal/ProjectsHut/assets/104740281/10342e49-daa0-4405-ae74-b6b90011037e) | ![image](https://github.com/priyankarpal/ProjectsHut/assets/104740281/f51d1639-7466-44a8-8d4d-706edf2fd10e) |
> chore: displaying social icons with valid social URL

- API/user.tsx
- DB/projects.json
- components/projects/ProjectList.tsx
Closes: #2018 
Streamlining Social Media Link Collection with GitHub API and removing social media link from projects db
> feat: streamlining Social Media Link Collection with GitHub API

- DB/projects.json
In the previous PR too many lines got changed to due prettier thats why a new pr @priyankarpal kindly merge :)
Sorry for incovenience.
I have added a nextjs project
fixes #2181
> chore: project addition by ratishjain

- DB/projects.json
#2413
project addition by JuanPabloDiaz 
N/A
> chore: Adding project developed by JuanPabloDiaz

- DB/projects.json
> chore: project addition by salmasyed19 #603

- app/globals.css
- app/layout.tsx
- components/AddYourProjectsGuide.tsx
- components/Footer.tsx
- components/MobileNavbar.tsx
- components/Navbar.tsx
- components/ThemeToggle.tsx
- components/landing/Banner.tsx
- components/landing/Home.tsx
- components/projects/ProjectCard.tsx
- components/projects/ProjectList.tsx
- components/projects/Projects.tsx
- tailwind.config.js
I have added functionality for users to choose between dark and light mode on the website. This is done through editing the tailwind CSS config and creating a handler for the two modes. 
Since the styling of the text and layout was hardcoded to be black, I have also made sure the text is readable and clear on both themes.
Here's how the different modes look on the Homepage and the Projects, though this applies to all of the pages.
<table>
<tr>
<td>
<br>Homepage - Light Mode
</td>
<td>
<br>Homepage - Dark Mode
</td>
</tr>
<tr>
<td>
<br>Projects - Light Mode
</td>
<td>
<br>Projects - Dark Mode
</td>
</tr>
</table>
> style: add dark mode toggle functionality
